### ISSUE TITLE
query for uuid in bindata field

### ISSUE THREAD

**Issue by kburger** [mongojack/mongojack#60]
given the mongo document:

```
{
    "_id": ObjectId("..."),
    "name": "example",
    "tag": BinData(3,"Yk2qH7ibk4vQ4XQ31kNCiw==")
}
```

I can query for this document using the regular java mongo driver like this:

```
MongoClient client = new MongoClient();
DB db = client.getDB("mydb");
DBCollection coll = db.getCollection("items");
String tagUuid = "8b939bb8-1faa-4d62-8b42-43d63774e1d0";
DBObject query = QueryBuilder.start("tag").is(UUID.fromString(tagUuid)).get();
DBCursor cursor = coll.find(query).limit(1);
System.out.println(cursor.hasNext());
```

will print `true`.

Using mongojack however, I do not get the same result:

```
// borrowing the same setup from the example above
JacksonDBCollection<Item,Object> jacksonColl = JacksonDBCollection.wrap(coll, Item.class);
// using the same query object as the example above
DBCursor<Item> cursor = jacksonColl.find(query).limit(1);
System.out.println(cursor.hasNext());
```

will print `false`.

Now I understand there are different ways of building the query. I've tried the following, but all with the same result:

```
jacksonColl.find().is("tag", UUID.fromString(tagUuid)).limit(1);
```

```
jacksonColl.find(DBQuery.is("tag", UUID.fromString(tagUuid)).limit(1);
```

As far as I could trace, the query object produces the right mongo query, but at some point it is serialized into the uuid string value. The serialization occurs in [SerializationUtils.java#L103](https://github.com/devbliss/mongojack/blob/master/src/main/java/org/mongojack/internal/util/SerializationUtils.java#L103) and [SerializationUtils.java#L128](https://github.com/devbliss/mongojack/blob/master/src/main/java/org/mongojack/internal/util/SerializationUtils.java#L128), IIRC.

Now this might be the wrong way to query for BinData fields with mongojack. If so, could someone point me to some examples on how to do it?

**Comment by kdkeck** [comment]
This was probably related to [https://jira.mongodb.org/browse/JAVA-403](https://jira.mongodb.org/browse/JAVA-403), which was fixed in version 3.0.0 of the Java Driver.  If it is now working as expected using that version of the Java Driver or newer, then please let us know so we can close this issue.  If not, please show us the source for the `Item` class so we can try to reproduce this issue.

**Comment by kburger** [comment]
I believe the problem remains. Mongojack serializes the uuid into a java string instead of storing it as a bindata object in mongo. The mongo driver handles this as expected, but mongojack does the serialization step. As far as I could see mongojack 2.3.0 uses mongo-java-driver 2.13.0, is there an easy way to let mongojack use 3.x?

The item class is a simple pojo:

```java
    @JsonIgnoreProperties(ignoreUnknown = true) // to ignore the _id field
    private static class Item {
        private String name;
        private UUID tag;
        
        public String getName() {
            return name;
        }
        
        public void setName(String name) {
            this.name = name;
        }
        
        public UUID getTag() {
            return tag;
        }
        
        public void setTag(UUID tag) {
            this.tag = tag;
        }
    }
```

**Comment by kburger** [comment]
I've made a quick example repo at [mongojack-uuid-example](https://github.com/kburger/mongojack-uuid-example).

**Comment by benmccann** [comment]
You have to use the latest mongojack from GitHub for the 3.0.0 driver. The latest released version does not use 2.13.0 yet

**Comment by kdkeck** [comment]
I see, it has nothing to do with the endian-ness issue.  If you want to compose a patch, you just need to create a simple UUIDSerializer, very similar to [ObjectIdSerializer](https://github.com/devbliss/mongojack/blob/master/src/main/java/org/mongojack/internal/ObjectIdSerializer.java) but without necessarily the need to support types in the model other than `java.util.UUID`, and add that serializer in [MongoJackSerializers](https://github.com/devbliss/mongojack/blob/master/src/main/java/org/mongojack/internal/MongoJackSerializers.java).  And add or modify a test to make sure it works as expected.

**Comment by kburger** [comment]
@kdkeck thanks, that seems like the best way to handle this situation. I'll look into a custom serializer if time permits. AFAIC this issue can be closed.
